language: node_js
node_js:
  - 5
cache:
  directories:
  - node_modules
install:
  - npm install -g jest-cli
  - npm install -g firebase-tools
after_success:
  - npm run test:coverage
  - firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}
